### PR TITLE
Use AGPL

### PR DESCRIPTION
**Pull request by JoshuaSlui**
I forgot PRs were necessary.
@Soapy7261 help me out here, turns out i've always used the wrong GNU

### CODE REVIEW

**Comment by JoshuaSlui** [comment]
I made the CLA, sweetheart.

**Comment by Soapy7261** [comment]
Sure, just don't forget about the other branches that have PRs

**Review by Soapy7261 — APPROVED** [review]
good

**Comment by JoshuaSlui** [comment]
> changes

The license should not conflict with any other PRs, as long as they pull it to their branch.

**Comment by Soapy7261** [comment]
oh right i forgot github isn't always fussy

**Pull request merged**
