### PR TITLE
might fix the issue idk

### PR DESCRIPTION
**Pull request by Soapy7261**
gonna see what pylint says and test it when im done eating (don't merge in the mean time)

### CODE REVIEW

**Comment by Soapy7261** [comment]
wait we don't have pylint anymore do we...

**Comment by Soapy7261** [comment]
oh its only on commits ffs

**Comment by Soapy7261** [comment]
probably works, probably doesn't.

**Comment by Soapy7261** [comment]
codeql you gonna...?

**Review by JoshuaSlui — APPROVED** [review]

**Pull request merged**
