### PR TITLE
Fix permission for /setserver

### PR DESCRIPTION
**Pull request by Soapy7261**
How did i forget

### CODE REVIEW

**Comment by Soapy7261** [comment]
What the fuck github i didn't add those 5 commits

**Comment by Soapy7261** [comment]
Hold on github is stupid

**Comment by Soapy7261** [comment]
PR is safe now, github scared me

**Comment by JoshuaSlui** [comment]
Sorry, is this PR actually ready for reviewal now? I'm a bit confused.

**Comment by Soapy7261** [comment]
its good now

**Review by JoshuaSlui — APPROVED** [review]

**Pull request merged**
