### PR TITLE
Sharding

### PR DESCRIPTION
**Pull request by Soapy7261**
# DO NOT MERGE UNTIL THE BOT HITS 1000 SERVERS OR MORE

### CODE REVIEW

**Comment by JoshuaSlui** [comment]
Does this.. also count not reviewing until the bot reaches 1k guilds?

**Comment by Soapy7261** [comment]
Nah you can review it, just don't merge

**Review by JoshuaSlui — DISMISSED** [review]

**Comment by Soapy7261** [comment]
i didn't do that github

**Comment by JoshuaSlui** [comment]
The ruleset did it for you through you

**Review by JoshuaSlui — APPROVED** [review]

**Pull request merged**
