### PR TITLE
Fix guild logs

### PR DESCRIPTION
**Pull request by JoshuaSlui**
Fixes IndexErrors within the sql statements checking blacklist statuses, this was the cause for guild joins and leaves not being logged.

### CODE REVIEW

**Review by Soapy7261 — APPROVED** [review]
don't bother asking for my review when its sql related, all ill do is just approve

**Comment by JoshuaSlui** [comment]
I kinda still gotta ask because i cant merge without a review lol

**Comment by JoshuaSlui** [comment]
Want me to ask a review from @ToothyDev for sql-related things from now on?

**Comment by Soapy7261** [comment]
Yes

**Pull request merged**
