### PR TITLE
Created README.md and changed prefix in bot's presence

### PR DESCRIPTION
**Pull request by Hilex23**

### CODE REVIEW

**Comment by FazeHedgehog** [comment]
I don't think it's a good idea to add the mention prefix in it like that.

**Comment by Hilex23** [comment]
So just type "mention"? Or how do you think it should be shown?

**Comment by FazeHedgehog** [comment]
Suppose something along the lines of `prefix: @mention`

**Comment by Hilex23** [comment]
Changed to `prefix: @mention`

**Comment by FazeHedgehog** [comment]
Good, lastly. The bot also displays software, you should probably add that

**Comment by Hilex23** [comment]
Done

**Pull request merged**
