### PR TITLE
Update dependencies 

### PR DESCRIPTION
**Pull request by Soapy7261**
# Updated dependencies:

## py-cord:
Was: 2.4.0
Now: 2.4.1

## mcstatus:
Was: 10.0.1
Now: 10.0.2

## python-dotenv:
Was: 0.21.0
Now: 0.21.1

### CODE REVIEW

**Comment by Soapy7261** [comment]
Also adds more versions to pylint, i forgot why i did it but i did

**Comment by Soapy7261** [comment]
CodeQL downloading seems to be broken, just ignore it

**Comment by JoshuaSlui** [comment]
Keeping this pending until github unbreaks.

**Comment by Soapy7261** [comment]
@MiataBoy it work now

**Comment by JoshuaSlui** [comment]
CodeQL begs to differ, but I don't see the use in codeQL for this anyways.

**Pull request merged**
